[project]
name = "dashboard"
version = "0.1.0"
description = "Dashboard for testing and creating user accounts and data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asgiref>=3.9.1",
    "django-cors-headers>=4.7.0",
    "django-stubs>=5.2.2",
    "django-stubs-ext>=5.2.2",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "djangorestframework-stubs>=3.16.2",
    "djangorestframework-types>=0.9.0",
    "dotenv>=0.9.9",
    "psycopg2-binary>=2.9.10",
    "pyjwt>=2.10.1",
    "pytz>=2025.2",
    "sqlparse>=0.5.3",
]
