[project]
name = "AlgoVictory"
version = "0.1.0"
description = "Match prediction Website django + react"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asgiref>=3.9.1",
    "cryptography>=46.0.4",
    "django>=5.2.5",
    "django-allauth>=65.14.0",
    "django-cors-headers>=4.7.0",
    "django-stubs>=5.2.2",
    "django-stubs-ext>=5.2.2",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "djangorestframework-stubs>=3.16.2",
    "djangorestframework-types>=0.9.0",
    "dotenv>=0.9.9",
    "googleauthentication>=0.0.18",
    "psycopg2-binary>=2.9.10",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.1",
    "pytz>=2025.2",
    "sendgrid>=6.12.5",
    "setuptools>=81.0.0",
    "sqlparse>=0.5.3",
    "stripe>=14.4.1",
]

[tool.django-stubs]
django_settings_module = "divinatio.settings"

[tool.pyright]
pythonVersion = "3.14"
