# Generated by Django 6.0.2 on 2026-03-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('dateTime', models.DateTimeField()),
                ('day', models.DateTimeField()),
                ('eventId', models.IntegerField()),
                ('leagueId', models.IntegerField()),
                ('name', models.TextField()),
                ('season', models.IntegerField()),
                ('shortName', models.IntegerField()),
                ('status', models.TextField()),
            ],
        ),
    ]
