# Generated by Django 6.0.2 on 2026-04-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sports', '0002_alter_upcomingevents_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevents',
            name='eventId',
            field=models.IntegerField(unique=True),
        ),
    ]
