# Generated by Django 6.0.2 on 2026-04-04 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sports', '0003_alter_upcomingevents_eventid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterModel',
            fields=[
                ('fighter_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FightFighterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField(blank=True, null=True)),
                ('moneyline', models.IntegerField(blank=True, null=True)),
                ('pre_fight_wins', models.IntegerField(blank=True, null=True)),
                ('pre_fight_losses', models.IntegerField(blank=True, null=True)),
                ('pre_fight_draws', models.IntegerField(blank=True, null=True)),
                ('pre_fight_no_contests', models.IntegerField(blank=True, null=True)),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.fightermodel')),
            ],
        ),
        migrations.RenameModel(
            old_name='UpcomingEvents',
            new_name='UpcomingEventsModel',
        ),
        migrations.CreateModel(
            name='FightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_id', models.IntegerField(unique=True)),
                ('weight_class', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fights',
                        to='sports.upcomingeventsmodel',
                        to_field='eventId',
                    ),
                ),
                (
                    'fighters',
                    models.ManyToManyField(
                        related_name='fights', through='sports.FightFighterModel', to='sports.fightermodel'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='fightfightermodel',
            name='fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.fightmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='fightfightermodel',
            unique_together={('fight', 'fighter')},
        ),
    ]
