# Generated by Django 6.0.2 on 2026-04-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sports', '0004_fightermodel_fightfightermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fightermodel',
            name='fighter_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
