# Generated by Django 6.0.2 on 2026-04-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sports', '0005_fightermodel_nickname_alter_fightermodel_fighter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightermodel',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='decision_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='knockout_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='no_contests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='reach',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='sig_strike_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='sig_strikes_landed_per_minute',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='submission_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='submission_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='takedown_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='technical_knockout_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='technical_knockout_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='technical_knockouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='title_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='title_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='title_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='weight_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fightermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
