# Generated by Django 6.0.2 on 2026-04-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_fightermodel_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('dateTime', models.DateTimeField()),
                ('day', models.DateTimeField()),
                ('eventId', models.IntegerField(unique=True)),
                ('leagueId', models.IntegerField()),
                ('name', models.TextField()),
                ('season', models.IntegerField()),
                ('shortName', models.TextField()),
                ('status', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
