# Generated by Django 6.0.2 on 2026-04-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sports', '0007_pasteventsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightermodel',
            name='imageURL',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
