# Generated by Django 6.0.2 on 2026-05-03 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_fightermodel_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AisResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatter', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='sports.upcomingeventsmodel', to_field='eventId')),
            ],
        ),
    ]
