# Generated by Django 5.2.9 on 2026-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
