# Generated by Django 6.0.4 on 2026-05-17 19:59

from django.db import migrations


def create_sites(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.get_or_create(id=2, defaults={'domain': '127.0.0.1:8000', 'name': '127.0.0.1:8000'})

    prod_site = Site.objects.filter(domain='algovictory.com').first()
    if prod_site is None:
        Site.objects.create(id=3, domain='algovictory.com', name='algovictory.com')
    elif prod_site.pk != 3:
        prod_site.delete()
        Site.objects.create(id=3, domain='algovictory.com', name='algovictory.com')


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_user_payment_date_user_payment_expires_user_premium'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(create_sites, migrations.RunPython.noop),
    ]
