# Generated by Django 6.0.2 on 2026-05-01 01:14

from django.db import migrations


def create_sites(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.get_or_create(domain='algovictory.com', defaults={'name': 'Site'})
    Site.objects.get_or_create(domain='127.0.0.1:8000', defaults={'name': 'Localhost'})


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(create_sites),
    ]
